// Generated by CoffeeScript 1.3.3
(function() {
  var MakeSync, Phantom, Sync, buildObjectOptions, createReplacement, phantom, _, _ref,
    __slice = [].slice;

  _ref = require('make-sync'), Sync = _ref.Sync, MakeSync = _ref.MakeSync;

  phantom = require('phantom');

  _ = require('underscore');

  buildObjectOptions = function(options) {
    return {
      create: {
        mode: options.mode,
        'sync-return': 'res'
      },
      ph: {
        mode: options.mode,
        exclude: [/^_/, 'exit'],
        'sync-return': 'res',
        num_of_args: {
          set: 2
        }
      },
      page: {
        mode: options.mode,
        exclude: [/^_/, 'sendEvent'],
        'sync-return': 'res',
        num_of_args: {
          set: 2
        }
      }
    };
  };

  createReplacement = function(options) {
    var objectOptions, replacement;
    objectOptions = buildObjectOptions(options);
    replacement = function() {
      var args, done, _i;
      args = 2 <= arguments.length ? __slice.call(arguments, 0, _i = arguments.length - 1) : (_i = 0, []), done = arguments[_i++];
      return phantom.create.apply(phantom, __slice.call(args).concat([function(ph) {
        var _createPage;
        _createPage = ph.createPage;
        ph.createPage = function() {
          var args, done, _j;
          args = 2 <= arguments.length ? __slice.call(arguments, 0, _j = arguments.length - 1) : (_j = 0, []), done = arguments[_j++];
          return _createPage.apply(null, __slice.call(args).concat([function(page) {
            var _evaluate, _evaluateSync;
            _evaluate = page.evaluate;
            _evaluateSync = MakeSync(_evaluate, {
              mode: 'sync',
              'sync-return': 'res'
            });
            MakeSync(page, objectOptions.page);
            if (_.isEqual(options.mode, ['mixed', 'args'])) {
              page.evaluate = function() {
                var args, cb, f, fargs, _k;
                args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
                f = args[0], fargs = 3 <= args.length ? __slice.call(args, 1, _k = args.length - 1) : (_k = 1, []), cb = args[_k++];
                if ((typeof cb) !== 'function') {
                  fargs.push(cb);
                  cb = null;
                }
                if ((typeof cb) !== 'function') {
                  return _evaluateSync.apply(page, args);
                } else {
                  return _evaluate.apply(page, args);
                }
              };
            }
            return done(page);
          }]));
        };
        MakeSync(ph, objectOptions.ph);
        return done(ph);
      }]));
    };
    return MakeSync(replacement, objectOptions.create);
  };

  Phantom = (function() {

    function Phantom(options) {
      if (options == null) {
        options = {
          mode: 'sync'
        };
      }
      this.create = createReplacement(options);
    }

    return Phantom;

  })();

  exports.Phantom = Phantom;

  exports.Sync = Sync;

}).call(this);
